use std::sync::atomic::{AtomicU64, Ordering};

use anyhow::{Context, Result, bail};
use reqwest::Client;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use serde_json::{Value, json};
use zcash_keys::address::Address;
use zcash_primitives::transaction::Transaction;
use zcash_protocol::consensus::{BlockHeight, BranchId};

use crate::wallet::regtest_network;

#[derive(Clone)]
pub struct NodeRpc {
    endpoint: String,
    client: Client,
    request_id: std::sync::Arc<AtomicU64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainInfo {
    pub chain: String,
    pub blocks: u64,
    #[serde(default)]
    pub bestblockhash: String,
    #[serde(default)]
    pub verificationprogress: f64,
}

#[derive(Debug, Deserialize)]
struct Envelope<T> {
    result: Option<T>,
    error: Option<Value>,
}

impl NodeRpc {
    pub fn new(endpoint: String) -> Self {
        Self {
            endpoint,
            client: Client::new(),
            request_id: Default::default(),
        }
    }

    pub async fn call<T: DeserializeOwned>(&self, method: &str, params: Value) -> Result<T> {
        let id = self.request_id.fetch_add(1, Ordering::Relaxed);
        let response = self
            .client
            .post(&self.endpoint)
            .timeout(std::time::Duration::from_secs(if method == "generate" {
                300
            } else {
                30
            }))
            .json(&json!({"jsonrpc":"2.0","id":id,"method":method,"params":params}))
            .send()
            .await
            .with_context(|| format!("calling Zakura {method}"))?;
        let status = response.status();
        if status == reqwest::StatusCode::UNAUTHORIZED {
            bail!(
                "Zakura RPC requires authentication; use the dedicated Regtest configuration generated by ths prepare"
            );
        }
        let envelope: Envelope<T> = response.json().await.context("decoding Zakura response")?;
        if let Some(error) = envelope.error {
            bail!("Zakura {method} failed: {error}");
        }
        if !status.is_success() {
            bail!("Zakura {method} returned HTTP {status}");
        }
        envelope
            .result
            .context("Zakura response did not contain a result")
    }

    pub async fn chain_info(&self) -> Result<ChainInfo> {
        self.call("getblockchaininfo", json!([])).await
    }
    pub async fn generate(&self, blocks: u32) -> Result<Vec<String>> {
        self.validate_network().await?;
        self.call("generate", json!([blocks])).await
    }

    pub async fn validate_network(&self) -> Result<ChainInfo> {
        let info: Value = self.call("getblockchaininfo", json!([])).await?;
        validate_network_info(&info)?;
        // Zakura reports BIP70 "test" for both Testnet and Regtest. Verify the
        // genesis block as well as the upgrade schedule before any mutation.
        let genesis: String = self.call("getblockhash", json!([0])).await?;
        anyhow::ensure!(
            genesis == "029f11d80ef9765602235e1bc9727e3eb6ba20839319f761fee920d63401e327",
            "ths requires the standard Regtest genesis block"
        );
        Ok(serde_json::from_value(info)?)
    }

    pub async fn validate_treasury(&self, address: &str) -> Result<()> {
        let template: Value = self.call("getblocktemplate", json!([])).await?;
        validate_treasury_template(&template, address)
    }
    pub async fn block(&self, id: &str) -> Result<Value> {
        self.call("getblock", json!([id, 2])).await
    }
    pub async fn transaction(&self, txid: &str) -> Result<Value> {
        self.call("getrawtransaction", json!([txid, 1])).await
    }
    pub async fn mempool(&self) -> Result<Vec<String>> {
        self.call("getrawmempool", json!([])).await
    }
}

fn validate_network_info(info: &Value) -> Result<()> {
    anyhow::ensure!(
        info["chain"]
            .as_str()
            .is_some_and(|s| s.eq_ignore_ascii_case("regtest") || s == "test"),
        "ths requires Regtest; node reports {}",
        info["chain"]
    );
    let upgrades = info["upgrades"]
        .as_object()
        .context("node omitted network upgrade information")?;
    let expected = [
        "Overwinter",
        "Sapling",
        "Blossom",
        "Heartwood",
        "Canopy",
        "NU5",
        "NU6",
    ];
    for name in expected {
        anyhow::ensure!(
            upgrades.values().any(|upgrade| upgrade["name"] == name
                && upgrade["activationheight"].as_u64() == Some(1)),
            "incompatible Regtest configuration: {name} must activate at block 1; use the configuration generated by ths"
        );
    }
    for upgrade in upgrades.values() {
        anyhow::ensure!(
            upgrade["name"]
                .as_str()
                .is_some_and(|name| expected.contains(&name)),
            "unsupported Regtest upgrade {}; use the configuration generated by ths",
            upgrade["name"]
        );
    }
    Ok(())
}

fn validate_treasury_template(template: &Value, address: &str) -> Result<()> {
    let params = regtest_network();
    let Some(Address::Transparent(expected)) = Address::decode(&params, address) else {
        bail!("invalid treasury address");
    };
    let height = u32::try_from(
        template["height"]
            .as_u64()
            .context("block template omitted height")?,
    )?;
    let raw = hex::decode(
        template
            .pointer("/coinbasetxn/data")
            .and_then(Value::as_str)
            .context("block template omitted coinbase transaction")?,
    )?;
    let tx = Transaction::read(
        &raw[..],
        BranchId::for_height(&params, BlockHeight::from_u32(height)),
    )?;
    anyhow::ensure!(
        tx.transparent_bundle().is_some_and(|bundle| bundle
            .vout
            .iter()
            .any(|output| output.recipient_address() == Some(expected)
                && u64::from(output.value()) > 0)),
        "Zakura mining payout does not match this wallet's treasury ({address}); restart your node with the configuration generated by ths prepare"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compatible_info() -> Value {
        let upgrades: serde_json::Map<String, Value> = [
            "Overwinter",
            "Sapling",
            "Blossom",
            "Heartwood",
            "Canopy",
            "NU5",
            "NU6",
        ]
        .into_iter()
        .map(|name| (name.into(), json!({"name":name,"activationheight":1})))
        .collect();
        json!({"chain":"regtest","upgrades":upgrades})
    }

    #[test]
    fn accepts_only_the_wallets_regtest_schedule() {
        let mut info = compatible_info();
        validate_network_info(&info).unwrap();
        info["chain"] = json!("test");
        validate_network_info(&info).unwrap();
        info["chain"] = json!("main");
        assert!(validate_network_info(&info).is_err());
        info = compatible_info();
        info["upgrades"]["NU6"]["activationheight"] = json!(2);
        assert!(validate_network_info(&info).is_err());
        info = compatible_info();
        info["upgrades"]["NU6.1"] = json!({"name":"NU6.1","activationheight":10});
        assert!(validate_network_info(&info).is_err());
    }

    #[test]
    fn requires_a_positive_coinbase_payment_to_the_prepared_treasury() {
        // Coinbase from a local Zakura getblocktemplate response (NU6, block 106).
        let raw = concat!(
            "050000800a27a7265510e7c8000000006a00000001",
            "0000000000000000000000000000000000000000000000000000000000000000",
            "ffffffff1a016a17f09f8cb83a20746875732d73706f6b652d7a616b757261ffffffff01",
            "40be4025000000001976a914ac84b19c72e770c4042c307da010fe70754e84da88ac000000"
        );
        let treasury = "tmRSYWtjmzRstCeX9c7hm8GsBRs4ndQshUf";
        let mut template = json!({"height":106,"coinbasetxn":{"data":raw}});
        validate_treasury_template(&template, treasury).unwrap();
        let error = validate_treasury_template(&template, "tmPSTyaDo5AngKdRPup6tSsjwzBFMFXbXJp")
            .unwrap_err();
        assert!(error.to_string().contains("mining payout does not match"));
        template["coinbasetxn"]["data"] =
            json!(raw.replace("40be402500000000", "0000000000000000"));
        assert!(validate_treasury_template(&template, treasury).is_err());
        template["coinbasetxn"]["data"] = json!("not hex");
        assert!(validate_treasury_template(&template, treasury).is_err());
        assert!(validate_treasury_template(&json!({"height":106}), treasury).is_err());
    }
}
