/** Truncates a hash for display: `cb45d3bb5…38905c`. */
export function shortHash(value: string, lead = 9, tail = 6): string {
  if (!value) return '—';
  if (value.length <= lead + tail) return value;
  return `${value.slice(0, lead)}…${value.slice(-tail)}`;
}

/**
 * The API serialises SQLite `CURRENT_TIMESTAMP`, which is UTC but carries no
 * timezone marker (`2026-09-17 10:31:48`). `new Date()` would read that as
 * local time and silently shift every timestamp by the UTC offset, so the
 * zone is made explicit before parsing.
 */
export function parseApiTimestamp(value: string): Date | null {
  if (!value) return null;
  const normalised = /[Zz]|[+-]\d{2}:?\d{2}$/.test(value)
    ? value.replace(' ', 'T')
    : `${value.replace(' ', 'T')}Z`;
  const parsed = new Date(normalised);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

const RELATIVE = new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' });
const DIVISIONS: Array<[Intl.RelativeTimeFormatUnit, number]> = [
  ['second', 60],
  ['minute', 60],
  ['hour', 24],
  ['day', 7],
  ['week', 4.35],
  ['month', 12],
  ['year', Number.POSITIVE_INFINITY],
];

/** Renders a timestamp as `just now`, `4 minutes ago`, `yesterday`, … */
export function timeAgo(value: string, now: Date = new Date()): string {
  const parsed = parseApiTimestamp(value);
  if (!parsed) return '—';

  let delta = (parsed.getTime() - now.getTime()) / 1000;
  if (Math.abs(delta) < 5) return 'just now';

  for (const [unit, span] of DIVISIONS) {
    if (Math.abs(delta) < span) return RELATIVE.format(Math.round(delta), unit);
    delta /= span;
  }
  return '—';
}

/** Absolute timestamp for tooltips and detail views. */
export function absoluteTime(value: string): string {
  const parsed = parseApiTimestamp(value);
  return parsed ? parsed.toLocaleString() : '—';
}

/**
 * Formats a node-reported block time. Regtest timestamps are generated by the
 * node rather than taken from the clock, so these are always labelled "chain
 * time" in the UI to distinguish them from wall-clock values like `created_at`.
 */
export function chainTime(unixSeconds: number | undefined): string {
  if (unixSeconds === undefined) return '—';
  return new Date(unixSeconds * 1000).toLocaleString();
}

export function chainTimeShort(unixSeconds: number): string {
  return new Date(unixSeconds * 1000).toLocaleTimeString();
}
